### ISSUE TITLE
To use 'zscore', the following product must be licensed, installed, and enabled:  

### ISSUE THREAD

**Issue by swsyoon** [YunweiZhang/ML-identify-battery-degradation#1]
Thank you for sharing the code. 

Do I need  matlab toolbox ,Statistics and Machine Learning Toolbox ?  

I can run "Multi_T_EIS_RUL_GPR.m" but the other two *.m files require " Statistics and Machine Learning Toolbox" from Matlab
for a function `zscore` . 

```
To use 'zscore', the following product must be licensed, installed, and
enabled:   Statistics and Machine Learning Toolbox ```

**Comment by YunweiZhang** [comment]
Hi,

‘zscore’ is for normalisation.
If you cannot use ‘zscore’, you can avoid using it by doing the normalisation by yourself. 
Just do it as it shown in “Multi_T_EIS_RUL_GPR.m”, e.g. (EIS-mean)/std, where the mean and std is “mean = mean(EIS_data,1); std = std(EIS_data,1);”

**Comment by swsyoon** [comment]
Thanks. I found the mfile in the MATLAB file exchange. 

https://www.mathworks.com/matlabcentral/fileexchange/74261-data-normalization
