### ISSUE TITLE
How to process the dataset

### ISSUE THREAD

**Issue by ydup** [YunweiZhang/ML-identify-battery-degradation#2]
Hi, what does the 'ox/red' mean in the source data of capacity? And could you please provide the data processing code?

**Comment by YunweiZhang** [comment]
ox/red = 1 represents the capacity after fully charge. ox/red = 0 is for the capacity after discharge.

**Comment by ydup** [comment]
@YunweiZhang Thanks, I process the discharge capacity curve of the battery 25C05 according to the maximum capacity with ox/red = 0 and draw the figures as follow,
![image](https://user-images.githubusercontent.com/43513009/100565691-1d075080-32ff-11eb-96d5-dc9d53d2281c.png)
And this is the curve of same battery in the Fig.1 of the paper, Identifying degradation patterns of lithium-ion batteries from impedance spectroscopy using machine learning,
![image](https://user-images.githubusercontent.com/43513009/100566201-5c826c80-3300-11eb-90d9-c94d2710c959.png)

Before the capacity degrades to 0.75, two curves are similar but the cycle number is totally different, could you please help?
Here is my code,
```python
import pickle
import matplotlib.pyplot as plt
import numpy as np

def sci_to_float(number):
    str_temp = number.partition('E')
    return float(str_temp[0])*pow(10,int(str_temp[-1]))

def read_q(path='./Q/Data_Capacity_45C01.txt'):
    with open(path) as file_in:
        lines = file_in.readlines()
        data = []
        flag_last = '1'
        capacity_last = '0E0'

        for idx, line in enumerate(lines):
            if idx != 0:
                temp_list = list(line.split())
                capacity_last = temp_list[-1]
                status = temp_list[2]
                cycle = temp_list[1]
                data.append([int(sci_to_float(cycle)), int(status), sci_to_float(capacity_last)])
    data = np.array(data)
    Q = []
    for idx in np.unique(data[:, 0]):
        if np.sum((data[:,0]==idx)&(data[:,1]==0)) != 0:
            Q.append([idx, np.max(data[(data[:,0]==idx)&(data[:,1]==0), 2])])
    Q = np.array(Q)
    return Q

data = read_q('./Q/Data_Capacity_25C05.txt')
plt.plot(Q[:, 0], Q[:, 1]/Q[0, 1])
```

**Comment by YunweiZhang** [comment]
The way you extract the data is ok. Please be notice that we collect the capacity at the even cycles, which means you have to time the cycle number by two!
If you do that, you will get the right plot.

**Comment by ydup** [comment]
@YunweiZhang Got it, thanks! 
And does it mean that we also need to time the cycles of EIS data by two?

**Comment by YunweiZhang** [comment]
Yes, exactly.

**Comment by ydup** [comment]
It's so kind of you. Thanks!
